version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 302361637558.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - docker build -t devops .
      - docker tag devops:latest 302361637558.dkr.ecr.us-east-1.amazonaws.com/devops:latest

  post_build:
    commands:
      - docker push 302361637558.dkr.ecr.us-east-1.amazonaws.com/devops:latest
